### ISSUE TITLE
Can’t pair with starling hub

### ISSUE THREAD

**Issue by jon6fingrs** [WebThingsIO/homekit-adapter#49]
I currently have homebridge paired with the HomeKit addon and working great. I purchased the starling hub so that I would basically have full nest integration. Whenever I try to pair it with my webthings server it says the PIN is invalid. The logs show this:

2020-03-10 19:43:21.971 INFO   : homekit-adapter: Found IP device: {
2020-03-10 19:43:21.972 INFO   : homekit-adapter:   name: 'Starling Home Hub 4DB8',
2020-03-10 19:43:21.972 INFO   : homekit-adapter:   address: '10.0.0.67',
2020-03-10 19:43:21.972 INFO   : homekit-adapter:   port: 45685,
2020-03-10 19:43:21.972 INFO   : homekit-adapter:   'c#': 2,
2020-03-10 19:43:21.973 INFO   : homekit-adapter:   ff: 0,
2020-03-10 19:43:21.973 INFO   : homekit-adapter:   id: '06:80:4D:2A:F8:8F',
2020-03-10 19:43:21.973 INFO   : homekit-adapter:   md: 'Starling Home Hub',
2020-03-10 19:43:21.973 INFO   : homekit-adapter:   pv: '1.1',
2020-03-10 19:43:21.973 INFO   : homekit-adapter:   's#': 1,
2020-03-10 19:43:21.974 INFO   : homekit-adapter:   sf: 1,
2020-03-10 19:43:21.974 INFO   : homekit-adapter:   ci: 2
2020-03-10 19:43:21.974 INFO   : homekit-adapter: }
2020-03-10 19:43:21.975 INFO   : homekit-adapter: Error loading device 06:80:4D:2A:F8:8F: Error: no pairing data available
2020-03-10 19:43:21.976 INFO   : homekit-adapter:     at /etc/webthings-gateway/addons/homekit-adapter/lib/homekit-device.js:105:15
2020-03-10 19:43:21.976 INFO   : homekit-adapter:     at processTicksAndRejections (internal/process/task_queues.js:94:5)

I was able to pair it with home assistant and with HomeKit without any issues. Do you think this is an issue with the HomeKit addon or with the starling hub?

Thanks!

**Comment by mrstegeman** [comment]
That log doesn’t actually show a pairing attempt. That’s just what is logged when the adapter first discovers the device but can’t find any existing pairing data.
