### ISSUE TITLE
Unable to re-add homekit-compatible wifi device (LED light)

### ISSUE THREAD

**Issue by KaiRo-at** [WebThingsIO/homekit-adapter#53]
I have a Eve LED light strip, which connects via wifi and I have operated with the 0.x gateway via the HomeKit adapter for quite a while, and continued to use after upgrade to 1.0 recently.
After I recently installed updates on my routers, which made the wifi be offline for a while temporarily, the gateway only displayed the LED strip as "THING" instead of the usual lightbulb, and I could not turn it off via the gateway in any more (I had turned it on via the gateway before this change). The light strip has a static DHCP lease set up, so is getting the same IP address internally all the time, and I can actually ping it on that, so it seems to be up correctly.
So I tried to fix the situation and removed it from the gateway and tried to re-add it. It is listed in the devices I can add, but when I enter the PIN and click "Submit", nothing happens for a while and it does not get added to the gateway again - finally "Incorrect PIN" appears even though what I used is the PIN on the sticker of the device (and as I said, I had it connected before, so the PIN worked previously).
Looking at the logs, it looks like there's some connection issue (I replaced the digits of the actual PIN with `*` symbols instead):
```
2020-12-14 15:12:53.406 INFO   : Opened a new things socket
2020-12-14 15:12:53.626 INFO   : About to call startPairing on ThingURLAdapter
2020-12-14 15:12:53.628 INFO   : About to call startPairing on HomeKitAdapter
2020-12-14 15:13:08.744 INFO   : About to call startPairing on ThingURLAdapter
2020-12-14 15:13:08.752 INFO   : About to call startPairing on HomeKitAdapter
2020-12-14 15:13:09.248 INFO   : Opened a new things socket
2020-12-14 15:13:31.318 INFO   : AdapterProxy: setPin: ***-**-*** for: homekit-5D:63:29:AE:65:AC
2020-12-14 15:14:08.756 INFO   : Pairing timeout
2020-12-14 15:15:31.818 INFO   : AdapterProxy: setPin: ***-**-*** for: homekit-5D:63:29:AE:65:AC
2020-12-14 15:15:42.281 INFO   : homekit-adapter: Pairing failed for device 5D:63:29:AE:65:AC: undefined
2020-12-14 15:15:42.283 ERROR  : homekit-adapter: AddonManagerProxy: Failed to set PIN for device homekit-5D:63:29:AE:65:AC
2020-12-14 15:15:42.285 ERROR  : Failed to set PIN for homekit-5D:63:29:AE:65:AC: undefined
2020-12-14 15:17:45.162 INFO   : homekit-adapter: Pairing failed for device 5D:63:29:AE:65:AC: undefined
2020-12-14 15:17:45.163 ERROR  : homekit-adapter: AddonManagerProxy: Failed to set PIN for device homekit-5D:63:29:AE:65:AC
2020-12-14 15:17:45.165 ERROR  : Failed to set PIN for homekit-5D:63:29:AE:65:AC: undefined
2020-12-14 15:25:40.933 ERROR  : Error getting thing description for thing with id homekit-5D:63:29:AE:65:AC: Error: Unable to find thing with id: homekit-5D:63:29:AE:65:AC
    at /home/pi/mozilla-iot/gateway/build/webpack:/src/models/things.js:268:1
2020-12-14 15:25:41.802 ERROR  : Error getting thing description for thing with id homekit-5D:63:29:AE:65:AC: Error: Unable to find thing with id: homekit-5D:63:29:AE:65:AC
    at /home/pi/mozilla-iot/gateway/build/webpack:/src/models/things.js:268:1
```
Is there anything I can do to check and fix the connection (as I said, I can actually ping the IP of the light strip, even from the gateway) or is this an issue of the gateway?

**Comment by KaiRo-at** [comment]
Another data point: Booting my laptop to Windows, I can launch Eve's "Elgato Control Center" app, which lists the light strip and can successfully change e.g. the color of the light, so the device is connected to the network, it's definitely the gateway that somehow is unable to communicate with it now.

**Comment by mrstegeman** [comment]
Can you try to factory reset the device, then set up the WiFi and try to pair it with the gateway again?

**Comment by mrstegeman** [comment]
Also, given that it’s an Eve device, I’m assuming it Bluetooth?

**Comment by KaiRo-at** [comment]
> Also, given that it’s an Eve device, I’m assuming it Bluetooth?

No, it's wifi, not bluetooth. I do have Bluetooth devices from them as well but https://www.evehome.com/en/eve-light-strip is connected via wifi.

If I can find out how to do the factory reset, I can try that. Just strange to me that it continues to work fine with their own app on a laptop but stopped working with the gateway. (And FWIW, removing the device from power and plugging back in doesn't work, as unplugging is what I have done in the last few days for turning it off.)

**Comment by KaiRo-at** [comment]
> Can you try to factory reset the device, then set up the WiFi and try to pair it with the gateway again?

All that said, for some reason, this worked. Sorry to bother you with this.

**Comment by mrstegeman** [comment]
No worries, glad that it's working now!
